### ISSUE TITLE
Quote of each time C++ kernel start-ups

### ISSUE THREAD

**Issue by shiroinekotfs** [shiroinekotfs/jupyter-cpp-kernel#24]
What do you guys think about displaying random quote of famous people on over the Internet (i.e. Dale Carnegie) everytime C++ kernel start-ups?

It will be funny, huh?

**Comment by TheFlightSimsOfficial** [comment]
> What do you guys think about displaying random quote of famous people on over the Internet (i.e. Dale Carnegie) everytime C++ kernel start-ups?
> 
> It will be funny, huh?

Dear god, who let you cook?

**Comment by shiroinekotfs** [comment]
Closed due to the useless of this sugguestion
